name: .NET Core CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2 
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.3
    - name: Install npm dependencies and build
      run: |
          npm i
          npm run build:prod
      working-directory: ./RestBnb/ClientApp
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run tests
      run: dotnet test --configuration Release
